=== andmikael/tms_pilot/schemas/optimization/opt_request.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "",
	"title": "JSON schema for data sent to optimization",
	"description": "Information about places to be visited and vehicles",
	"type": "object",
	"properties": {
		"addresses": {
			"description": "List of coordinates to be visited",
			"type": "array",
			"items": {
				"type": "float"
			},
			"minItems": 1,
			"uniqueItems": true
		},
		"number_of_vehicles": {
			"description": "Number of vehicles",
			"type": "integer"
		},
		"start_time": {
			"description": "Start time of delivery",
			"type": "string"
		},
		"must_visit": {
			"description": "List of lists of indices of the address array that MUST be visited, one for each vehicle",
			"type": "array",
			"items": {
				"type": "array",
				"items": {
					"type": "integer"
				}
			},
			"minItems": 1,
			"uniqueItems": false
		},
		"traffic_mode": {
			"description": "Traffic mode",
			"type": "string",
			"enum": [
				"best_guess",
				"optimistic",
				"pessimistic"
			]
		},
		"start_indexes": {
			"description": "List of start locations of each vehicle in order, defined as indices of the list of addresses",
			"type": "array",
			"items": {
				"type": "integer"
			},
			"minItems": 1,
			"uniqueItems": false
		},
		"end_indexes": {
			"description": "List of end locations of each vehicle in order, defined as indices of the list of addresses",
			"type": "array",
			"items": {
				"type": "integer"
			},
			"minItems": 1,
			"uniqueItems": false
		}
	},
	"required": [
		"addresses",
		"number_of_vehicles",
		"start_time",
		"must_visit",
		"start_indexes",
		"end_indexes"
	]
}

=== andmikael/tms_pilot/schemas/optimization/opt_request_example.json
{"addresses": ["Prannarintie+8+Kauhajoki", "Prannarintie+10+Kauhajoki", "Topeeka+26+Kauhajoki", "Elamanaukio+2+Tampere", "Puijonlaaksontie+2+Kuopio"],
       "start_indexes": [0, 1],
       "end_indexes": [0, 2],
       "start_time": "9:00",
       "must_visit": [[1], [3]],
       "traffic_mode": "best_guess",
       "number_of_vehicles": 2}
